# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdp < Formula
  desc "Multi-dev proxy — run multiple dev servers behind one port"
  homepage "https://github.com/drgould/multi-dev-proxy"
  version "1.1.1"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/drgould/multi-dev-proxy/releases/download/v1.1.1/mdp_darwin_amd64.tar.gz"
      sha256 "8dfd420bde96d0be0f7c77969faabbd126db116f35be02d4f2571636a5982a08"

      define_method(:install) do
        bin.install "mdp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/drgould/multi-dev-proxy/releases/download/v1.1.1/mdp_darwin_arm64.tar.gz"
      sha256 "1ed91dd4cb2275ff9048ae246e3d47c2333e3a7e37577292376dec147f63701a"

      define_method(:install) do
        bin.install "mdp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/drgould/multi-dev-proxy/releases/download/v1.1.1/mdp_linux_amd64.tar.gz"
      sha256 "fbe29e323b42de4328b4df3e4e957ece0bbe5621a3084ef6b5bdb69a3f0fc6bf"
      define_method(:install) do
        bin.install "mdp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/drgould/multi-dev-proxy/releases/download/v1.1.1/mdp_linux_arm64.tar.gz"
      sha256 "105b2f7786d0eea76fd5c4892d5fc7ebfe1365bb1061fc32e9573d7fe8c7dccb"
      define_method(:install) do
        bin.install "mdp"
      end
    end
  end
end
