# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdp < Formula
  desc "Multi-dev proxy — run multiple dev servers behind one port"
  homepage "https://github.com/drgould/multi-dev-proxy"
  version "1.1.1"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/drgould/multi-dev-proxy/releases/download/v1.1.1/mdp_darwin_amd64.tar.gz"
      sha256 "73677dbc4efea5162f4da6806a5ca71184c1da4bb06073d5a72bf1ececded843"

      define_method(:install) do
        bin.install "mdp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/drgould/multi-dev-proxy/releases/download/v1.1.1/mdp_darwin_arm64.tar.gz"
      sha256 "9ade1a2847d14e66bbb930484d71de030d03665dc05cde51599742bb61d42974"

      define_method(:install) do
        bin.install "mdp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/drgould/multi-dev-proxy/releases/download/v1.1.1/mdp_linux_amd64.tar.gz"
      sha256 "4d0e0a1ad5437f473571a0bfecbd7f77729eddf08c5f50ff2cbac8bcade4b243"
      define_method(:install) do
        bin.install "mdp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/drgould/multi-dev-proxy/releases/download/v1.1.1/mdp_linux_arm64.tar.gz"
      sha256 "d5ad704dc11fb7450d8fcb1f3b71153168f1a9daf1be866dd247e179cb8ceab8"
      define_method(:install) do
        bin.install "mdp"
      end
    end
  end
end
