# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdp" do
  version "1.1.2"

  on_intel do
    url "https://github.com/drgould/multi-dev-proxy/releases/download/v#{version}/mdp_darwin_amd64.tar.gz"
    sha256 "0aa27efcab723aa00c28c1f462617406492acfbae1a86d207d68f3833b43f657"
  end
  on_arm do
    url "https://github.com/drgould/multi-dev-proxy/releases/download/v#{version}/mdp_darwin_arm64.tar.gz"
    sha256 "96134306c88f188baf17712aeef41a02a7431155e7d92c47d10d7bf3b616f758"
  end

  name "mdp"
  desc "Multi-dev proxy — run multiple dev servers behind one port"
  homepage "https://github.com/drgould/multi-dev-proxy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdp"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-cr", "#{staged_path}/mdp"]
  end

  # No zap stanza required
end
