# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdp" do
  version "1.4.1"

  on_macos do
    on_intel do
      sha256 "a0469f969473747cef3159f97973244c98590042371462cfd8b248ac382ef7e5"
      url "https://github.com/drgould/multi-dev-proxy/releases/download/v#{version}/mdp_darwin_amd64.tar.gz",
        verified: "github.com/drgould/multi-dev-proxy"
    end
    on_arm do
      sha256 "b193b14bd70d4f27265a481c8f3512d9508449b098f0b42162d91cfbd8f7d68d"
      url "https://github.com/drgould/multi-dev-proxy/releases/download/v#{version}/mdp_darwin_arm64.tar.gz",
        verified: "github.com/drgould/multi-dev-proxy"
    end
  end

  on_linux do
    on_intel do
      sha256 "8b90577f0b0d073da500d076ab34b70e88cac05cca2e9e25fc4fa103fc59f000"
      url "https://github.com/drgould/multi-dev-proxy/releases/download/v#{version}/mdp_linux_amd64.tar.gz",
        verified: "github.com/drgould/multi-dev-proxy"
    end
    on_arm do
      sha256 "0c541b31b84f850a5fb332467d74769589fd370ddfac9bd840a390c689162776"
      url "https://github.com/drgould/multi-dev-proxy/releases/download/v#{version}/mdp_linux_arm64.tar.gz",
        verified: "github.com/drgould/multi-dev-proxy"
    end
  end

  name "mdp"
  desc "Multi-dev proxy — run multiple dev servers behind one port"
  homepage "https://github.com/drgould/multi-dev-proxy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdp"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mdp"]
  end

  # No zap stanza required

end
