# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdp" do
  version "1.7.0"

  on_macos do
    on_intel do
      sha256 "084ac96d2297e68a22dd43fd45cc2793d831ebc0beb5b933a0c49f220f3f5720"
      url "https://github.com/drgould/multi-dev-proxy/releases/download/v#{version}/mdp_darwin_amd64.tar.gz",
        verified: "github.com/drgould/multi-dev-proxy"
    end
    on_arm do
      sha256 "892d49f29196549ff2bb6c9e13486a3561a76af5d693ddd70b8d17ed786dfd2f"
      url "https://github.com/drgould/multi-dev-proxy/releases/download/v#{version}/mdp_darwin_arm64.tar.gz",
        verified: "github.com/drgould/multi-dev-proxy"
    end
  end

  on_linux do
    on_intel do
      sha256 "280426c41d049509316645b191e89e4a862d7be0718d4e5f4b9d1bf85ccf3f88"
      url "https://github.com/drgould/multi-dev-proxy/releases/download/v#{version}/mdp_linux_amd64.tar.gz",
        verified: "github.com/drgould/multi-dev-proxy"
    end
    on_arm do
      sha256 "cf0607a741478569cbd3a4134050d8954ced6c55345416943c70390f92473c26"
      url "https://github.com/drgould/multi-dev-proxy/releases/download/v#{version}/mdp_linux_arm64.tar.gz",
        verified: "github.com/drgould/multi-dev-proxy"
    end
  end

  name "mdp"
  desc "Multi-dev proxy — run multiple dev servers behind one port"
  homepage "https://github.com/drgould/multi-dev-proxy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdp"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mdp"]
  end

  # No zap stanza required

end
