# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdp < Formula
  desc "Multi-dev proxy — run multiple dev servers behind one port"
  homepage "https://github.com/drgould/multi-dev-proxy"
  version "1.9.0"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/drgould/multi-dev-proxy/releases/download/v1.9.0/mdp_darwin_amd64.tar.gz"
      sha256 "8b4099968091cb3b6dffdf0cdecc664821105715d081325408656c7d4c7d7926"

      define_method(:install) do
        bin.install "mdp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/drgould/multi-dev-proxy/releases/download/v1.9.0/mdp_darwin_arm64.tar.gz"
      sha256 "de6d645747ca5687e06ff41b0dc1e78b6efc1ae2292335eb468bd5de64c6165d"

      define_method(:install) do
        bin.install "mdp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/drgould/multi-dev-proxy/releases/download/v1.9.0/mdp_linux_amd64.tar.gz"
      sha256 "1004ae9cba24eb086cb82dd0c4453bf19c7545f76474582d6cce70040dbfabc4"
      define_method(:install) do
        bin.install "mdp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/drgould/multi-dev-proxy/releases/download/v1.9.0/mdp_linux_arm64.tar.gz"
      sha256 "dbff30ac3b7a7d5f7b2ae5803a08c8fe5556a41f36915ba18380b9548fac2b0f"
      define_method(:install) do
        bin.install "mdp"
      end
    end
  end

  test do
    assert_match "mdp", shell_output("#{bin}/mdp --help")
  end
end
